const INVALID_DATA_ERROR = 400;
const SERVER_ERROR = 500;
const NOT_FOUND_ERROR = 404;
const FORBIDDEN_ERROR = 403;
const AUTH_ERROR = 401;
const CONFLICT_ERROR = 409;

module.exports = {
  INVALID_DATA_ERROR,
  SERVER_ERROR,
  NOT_FOUND_ERROR,
  FORBIDDEN_ERROR,
  AUTH_ERROR,
  CONFLICT_ERROR,
};
